# Generated by Django 4.2.7 on 2025-07-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
